title: Disc-Sim
email: spencer.henry182@myci.csuci.edu
description: >
  This is the background or introduction of your project. You can elaborate on what the project is about, its goals, and any other relevant information.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
include:
  - _pages
